wait port 8545, enable resume

diff --git a/.github/workflows/rpc-integration-tests.yml b/.github/workflows/rpc-integration-tests.yml
--- a/.github/workflows/rpc-integration-tests.yml
+++ b/.github/workflows/rpc-integration-tests.yml
@@ -57,6 +57,21 @@ jobs:
         run: |
           python3 $ERIGON_QA_PATH/test_system/db-producer/pause_production.py || true
 
+      - name: Wait for port 8545 to be opened
+        run: |
+          for i in {1..30}; do
+            if nc -z localhost 8545; then
+              echo "Port 8545 is open"
+              break
+            fi
+            echo "Waiting for port 8545 to open..."
+            sleep 10
+          done
+          if ! nc -z localhost 8545; then
+            echo "Port 8545 did not open in time"
+            exit 1
+          fi
+
       - name: Start Silkworm RpcDaemon
         working-directory: ${{runner.workspace}}/silkworm/build/cmd
         run: |
@@ -67,6 +82,8 @@ jobs:
       - name: Run RPC Integration Tests
         id: test_step
         run: |
+          set +e # Disable exit on error
+          
           # Run RPC integration test runner via http
           ${{runner.workspace}}/silkworm/.github/workflows/run_integration_tests.sh ${{runner.workspace}}/rpc-tests/integration ${{runner.workspace}}/silkworm/build/cmd/jwt.hex $RPC_PAST_TEST_DIR/mainnet_$(date +%Y%m%d_%H%M%S)_integration_$(git -C ${{runner.workspace}}/silkworm rev-parse --short HEAD)_http/ 
 
@@ -85,8 +102,7 @@ jobs:
         run: |
           ${{runner.workspace}}/silkworm/.github/workflows/stop_integration_rpcdaemon.sh $RPC_DAEMON_PID
 
-      - name: Resume the Erigon instance dedicated to db maintenance
-        if: false # disabled while running RpcDaemon attached to E3 using gRPC
+      - name: Resume the Erigon instance dedicated to db maintenance, if crashed or paused
         run: |
           python3 $ERIGON_QA_PATH/test_system/db-producer/resume_production.py || true
 
