display failed tests

diff --git a/.github/workflows/snapshot-test.yml b/.github/workflows/snapshot-test.yml
--- a/.github/workflows/snapshot-test.yml
+++ b/.github/workflows/snapshot-test.yml
@@ -48,24 +48,38 @@ jobs:
         working-directory: ${{runner.workspace}}/silkworm/build/cmd
         run: |
           set +e # Disable exit on error
+          
+          # Initialize the variables to collect failed test names and the overall test exit status
+          failed_tests=""
           test_exit_status=0
           
-          # Run the test script
-          ./snapshots --snapshot_dir $ERIGON_SNAPSHOT_TEST_DIR count_headers
-          test_exit_status=$(( test_exit_status != 0 || $? != 0 ))
-          ./snapshots --snapshot_dir $ERIGON_SNAPSHOT_TEST_DIR count_bodies
-          test_exit_status=$(( test_exit_status != 0 || $? != 0 ))
+          # Run the first count_headers script
+          ./snapshots --snapshot_dir "$ERIGON_SNAPSHOT_TEST_DIR" count_headers
+          exit_status=$?
+          if [ $exit_status -ne 0 ]; then
+            failed_tests="$failed_tests count_headers"
+            test_exit_status=1
+          fi
+          
+          # Run the second count_bodies script
+          ./snapshots --snapshot_dir "$ERIGON_SNAPSHOT_TEST_DIR" count_bodies
+          exit_status=$?
+          if [ $exit_status -ne 0 ]; then
+            failed_tests="$failed_tests count_bodies"
+            test_exit_status=1
+          fi
           
           # Save the subsection reached status
           echo "::set-output name=test_executed::true"
           
           # Check test runner exit status
-          if [ $test_exit_status -eq 0 ]; then
-            echo "tests completed successfully"
+          if [ "$test_exit_status" -eq 0 ]; then
+            echo "Tests completed successfully."
             echo "TEST_RESULT=success" >> "$GITHUB_OUTPUT"
           else
-            echo "error detected during tests"
-            echo "TEST_RESULT=failure" >> "$GITHUB_OUTPUT"            
+          # Output the list of failed tests without commas
+            echo "Error detected during tests:$failed_tests"
+            echo "TEST_RESULT=failure" >> "$GITHUB_OUTPUT"
           fi
 
       - name: Resume the Erigon instance dedicated to db maintenance
